In [1]:
import numpy as np
import sys
import json
import os
import random
import copy

def read_data(dir_str):
# 从文件中读取矩阵
    A = []
    temp=[]
    with open(dir_str) as fdata:
        while True:
            line=fdata.readline()
            if not line:
                break
            p = []
            temp = line.split(' ')
            for t in temp:
                t = int(t)
                p.append(t)
            A.append(p)
    return A

def get_location(mat, element):
# 获取element在mat中的位置,返回坐标i, j
    row_num = mat.shape[0]
    col_num = mat.shape[1]
    
    for i in range(row_num):
        for j in range(col_num):
            if element == mat[i][j]:
                return i, j

def get_actions(mat):
# 获取mat中的0元素可以移动的下一个位置，返回可移动动作的列表
    row_num = mat.shape[0]
    col_num = mat.shape[1]
    
    (x, y) = get_location(mat, 0)
    action = [(0, 1), (0, -1), (1, 0), (-1, 0)]  # action：朝4个方向分别移动1格
    
    # 0在边缘:可以减少可执行的action
    if x == 0:
        action.remove((-1, 0))
    if y == 0:
        action.remove((0, -1))
    if x == row_num - 1:
        action.remove((1, 0))
    if y == col_num - 1:
        action.remove((0, 1))
        
    # 0元素执行action，两个元素交换位置
    idx = random.randint(0, len(action)-1)
    (a, b) = np.array(action)[idx]
    n = mat[x+a][y+b]
    s = copy.deepcopy(mat)
    s[x+a][y+b] = 0
    s[x][y] = n
    
    return s

In [2]:
dir = "config.json"
while not os.path.exists(dir):
# 判断文件是否存在
    print("file doesn't exists!")
    sys.exit()
f = open(dir, encoding='utf-8')
setting = json.load(f)
f.close()

print('读取矩阵的行数')
num = int(setting['num'])
print("求解%d-数码问题"%(num ** 2 - 1))
    
print("读取目标矩阵B")
B = read_data(setting['arrayB'])
matB = np.array(B)
print(matB)

读取矩阵的行数
求解24-数码问题
读取目标矩阵B
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24  0]]


In [3]:
for i in range(100):
    matB = get_actions(matB)

print(matB) 

[[ 1  2 10 14  4]
 [ 6  0  7  3  5]
 [11 12 13  9 15]
 [22 21  8 18 19]
 [16 23 17 24 20]]


In [4]:
resultfile = "arrayA_" + str(setting['num']) + ".txt"
h = open(resultfile, 'w', encoding='utf-8')
h.write(str(matB))

90